apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-user-onboarding
  title: Onboard GitHub User to Org
  description: Invites a user to the Org and initializes a repo with CODEOWNERS.
  tags:
    - admin
    - github
spec:
  owner: user:pakaashok
  type: service

  parameters:
    - title: Onboarding Details
      required: [githubUser, repoName]
      properties:
        githubUser:
          type: string
          title: GitHub Username
          description: The user to invite and add to CODEOWNERS.
        repoName:
          type: string
          title: New Repository Name

  steps:
    - id: fetch-base
      name: Prepare Onboarding Files
      action: fetch:template
      input:
        url: ./onboarding-skeleton # A separate skeleton folder
        values:
          githubUser: ${{ parameters.githubUser }}

    - id: publish
      name: Initialize Onboarding Repo
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: 'github.com?owner=pakaashok&repo=${{ parameters.repoName }}'
        description: 'Onboarding repo for ${{ parameters.githubUser }}'

        